### ISSUE TITLE
sowing species ingress-controller has no deployed releases

### ISSUE THREAD

**Issue by lklkxcxc** [gardener/garden-setup#170]
**What happened**:
sow deploy -A
**What you expected to happen**:
`*** sowing species ingress-controller
no plugins found for action prepare
executing configured plugins for action deploy
using config from path ingresscontroller
Plugin: helm[deploy]{ingresscontroller} (/sow/plugins/helm/plugin)
    using /mounted/root/jiawen/landscape/./kubeconfig
Running helm upgrade for nginx-ingress-controller ...
Error: UPGRADE FAILED: "nginx-ingress-controller" has no deployed releases
command failed, waiting for 15 seconds and trying again (4 times)
Error: UPGRADE FAILED: "nginx-ingress-controller" has no deployed releases
command failed, waiting for 15 seconds and trying again (3 times)
Error: UPGRADE FAILED: "nginx-ingress-controller" has no deployed releases
command failed, waiting for 15 seconds and trying again (2 times)
Error: UPGRADE FAILED: "nginx-ingress-controller" has no deployed releases
command failed, waiting for 15 seconds and trying again (1 times)
Error: UPGRADE FAILED: "nginx-ingress-controller" has no deployed releases
Error: helm command failed and retry limit reached`
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Version of garden-setup (release or commit)：`origin/master`
- Versions of components (only needed if you overwrote the defaults)
- Where does the underlying base cluster come from and which operating system does it use?
- Which cloud provider is configured for the setup?:`openstack`
- Other:

**Comment by Diaphteiros** [comment]
This is (probably) not really a bug in garden-setup or sow itself, but helm3 sometimes failing for unknown reasons. 
I have an idea for a workaround that will solve this issue. I'll have a look.

**Comment by lklkxcxc** [comment]
@Diaphteiros Helm version is 2.2.2 and kube version is 1.16.4

`[root@test-k8s-1 ~]# helm version
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
[root@test-k8s-1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by Diaphteiros** [comment]
That depends. I assume that you use the docker binary of sow (`docker/bin/sow` and not `bin/sow` in the sow repo), which brings its own helm in the image. This one is helm3: https://github.com/gardener/sow/blob/master/docker/Dockerfile#L25

Since garden-setup does not deploy tiller anymore, using the current version of garden-setup with helm2 is only possible, if you deploy tiller yourself. 

The workaround that I implemented (https://github.com/gardener/garden-setup/pull/171) should work anyway: It uses "helm template" and sow's "kubectl" plugin to deploy resources in the cluster instead of deploying via helm. Because the kubectl plugin has its own state management, there shouldn't be any disadvantages (at least I can't think of any right now), but hopefully the stability will improve a little bit. 

The PR is currently being tested and will be merged as soon as this is done.

**Comment by Diaphteiros** [comment]
I made a new release of garden-setup that includes the described workaround.
Please be aware that you have to update `sow` to the newest release and deploying over an existing landscape might cause unexpected results and is discouraged.
