### ISSUE TITLE
How can I setup garden in alicloud?

### ISSUE THREAD

**Issue by knightXun** [gardener/garden-setup#248]
How can I setup garden in alicloud? The readme only tell me how to setup garden on gcp. Seems not friendly for somebody dont has gcp k8s like me. It will be better to setup garden on any Iaas not only gcp.

**Comment by knightXun** [comment]
Ps, the setup scripts seem too complicated

**Comment by Diaphteiros** [comment]
Garden-setup actually supports creating a Gardener landscape on GCP, AWS, Azure, or OpenStack. AliCloud is currently not supported and probably won't be added in the foreseeable future.

A complete Gardener landscape consists of more than just the Gardener itself and is quite complex. It includes an ingress controller, the 'virtual cluster' consisting of kube-apiserver, kube-controller-manager and etcd, as well as extensions for the Gardener and configuration for it (cloudprofiles, seeds, ...), the Gardener dashboard, and some more components. Due to this complexity, setting up a full Gardener landscape isn't easy either.
Garden-setup aims at providing an easy-to-consume solution for setting up a landscape while still providing enough configuration options to adjust the landscape to your needs. However, the price for abstracting this complex setup to basically one single configuration file that supports multiple scenarios for multiple cloudproviders is that garden-setup is complex behind the scenes too. As long as your use-case fits one of the use-cases garden-setup was designed for, it is probably the easiest way to get a Gardener landscape up and running. If your use-case doesn't fit and you have to understand what garden-setup does in detail in order to manipulate it, you face the complexity of setting up a Gardener landscape, mixed with the abstractions from garden-setup and the somewhat unintuitive yaml syntax of a `sow` module.

I'm afraid there is no nice solution for this. The problem itself is complex, and an installer that provides an easy interface while still allowing for some customization won't be less complex either.
