### ISSUE TITLE
EKS support

### ISSUE THREAD

**Issue by litalec** [gardener/garden-setup#276]
**What would you like to be added**:
Support for installation on EKS.

Currently the advice is to "use KOPS or GKE".

**Why is this needed**:
Not supporting EKS is cutting off a large chunk of potential users.

**Comment by Diaphteiros** [comment]
We propose GKE or `kops` because of ease of use. The user experience with EKS is not comparable. EKS is a very new service and behind their competitors. It's a lot do-it-yourself (IaaS resources, kube-system components, upgrades), so we naturally do no recommend it. 
See also https://cloudacademy.com/blog/kubernetes-services-aws-vs-azure-vs-google-cloud/ -> “Automatic Update: Upgrading Amazon EKS, a user needs to send some command-line instructions to it, which makes it more difficult [than AKS and GKE].” or https://logz.io/blog/kubernetes-as-a-service-gke-aks-eks -> “Automatic Update: Amazon EKS has the most difficult upgrade steps, and the user needs to send some command-line instructions to it, especially when upgrading nodes."
 
In terms of "large chunk of potential users", we cannot tell, but we don't see that. Many people talk about EKS (side-by-side with AKS and GKE), because it's AWS, but it is fairly new/still early and we do not see much pull here. This also matches what we hear elsewhere or you can hear yourself, e.g. Corey Quinn from https://www.lastweekinaws.com: “EKS, their managed Kubernetes project, is still…, kind of sad.”.


It's not that EKS is not supported, garden-setup can work on EKS too, see for example here: https://medium.com/@niyazi_erd/kubernetes-clusters-as-a-service-with-gardener-8a4f71412261
But it seems that it is more difficult to configure the 'base cluster' correctly on EKS compared to GKE or kops, since several people have had problems with EKS in the past. 
So the comment in the README is not meant as 'doesn't work on EKS, please use something else' but instead as 'you can use EKS, but be prepared that it might be more difficult than on a cluster created by GKE or kops and we are currently lacking documentation to compensate for that'.

Nontheless, I agree with you that we should improve the documentation regarding EKS.

**Comment by Diaphteiros** [comment]
With the [landscaper](https://github.com/gardener/landscaper) coming closer to the finish line, I doubt someone will take the time to write an extensive documentation for EKS.
