### ISSUE TITLE
Add annotations for the ingress service via acre.yaml

### ISSUE THREAD

**Issue by hassbert** [gardener/garden-setup#298]
**What would you like to be added**:
Add the option to add annotations to the ingress service via the acre.yaml:
https://github.com/gardener/garden-setup/blob/master/components/ingress-controller/chart/templates/00-ingress-controller.yaml#L248

I could imagine something like
```
landscape:
  ingress:
    annotations:
      my-annotation: "true"
```

**Why is this needed**:
This would enable us to use internal loadbalancers for the garden cluster itself (gardener dashboard, api, etc.) by adding the annotation `service.beta.kubernetes.io/aws-load-balancer-internal: "true"`.
In general that would enhance the possibilities of customization of the gardener setup via the acre.yaml.

**Comment by hassbert** [comment]
If the issue makes sense I'd also happy to contribute and implement it by myself. But as I am really new to gardener a little introductory session on how sow and the garden-setup works would be highly appreciated :) .

**Comment by Diaphteiros** [comment]
I think this makes sense. I'm not really familiar with ingresses - where do you need this annotation? On the `nginx` somewhere, on one specific ingress resource, or on each ingress resource? In the last case, it might be a little more difficult, since most of the ingresses are created by Gardener itself (although there might be an option to pass ingress annotations through, I don't know that).
I can give you a short introduction into how garden-setup works, just message me on slack (Diaphteiros).

**Comment by HerrmannHinz** [comment]
this can be closed eh? should be solved via the merged PR. 
cc @Diaphteiros @hassbert
