### ISSUE TITLE
"gardener/virtual" Installation Fail 

### ISSUE THREAD

**Issue by hfmartinez** [gardener/garden-setup#327]
I'm currently doing the gardener installation process, on one side I have a cluster in virtual machines, and on the other side AKS, I already made the process of verification and compilation of the acre.yaml file, but at the time of installation the process to in the `"gardener / virtual"` section, report an error, the error is 

```
no such hostUnable to connect to the server: dial tcp: lookup api.ing.test.rescitygardener.com on 10.0.2.3:53: no such host
"where"
``` 

_test.rescitygardener.com_ is the lanscape.domain from acre.yaml.

Could you explain to me what parameter I can place in that section of the acre.yaml or if it is necessary to have an external DNS, this could be taken from azure? as a DNS zone?

thanks.

**Comment by Diaphteiros** [comment]
The error means that your 'virtual' cluster is not reachable. There are two common reasons for this:
1. The kube-apiserver deployment is not ready. This happens mostly due to the etcd not being ready. To verify, check the pods in the `garden` namespace on your base cluster - is the `gardener-kube-apiserver` running?
2. DNS resolution does not work. To verify, check the `DNSEntry` resource in your cluster. Is it `Ready`? If not, check the status of the `DNSProvider`. Do a `kubectl describe` on it - what does the error say?

The domain under `landscape.domain` should be a sub-domain of a domain that is manageable by the provided DNS provider.
If you don't specify the DNS provider, it will be defaulted to the one of your "base infrastructure" (Azure in your case, if I understood correctly). So, for the `test.rescitygardener.com` to work, garden-setup needs to be able to manage `rescitygardener.com` with the provided Azure credentials.

**Comment by hfmartinez** [comment]
I ran the next command to see the state of pods, deployments, and services from the garden namespace.

`
kubectl get pods,deployments,svc --namespace=garden
`
this is the result. 
![image](https://user-images.githubusercontent.com/49379467/97709678-05983600-1abb-11eb-9aa2-16944629ee1f.png)

currently, my aks cluster has only 2 nodes, is it sufficient?

**Comment by Diaphteiros** [comment]
That strongly depends on the size of your nodes ;-)

From the README:
- Your base cluster needs at least 4 nodes with a size of 8GB for each node
  - This is only a rough estimate for the required resources, you can also use fewer or more nodes if the node size is adjusted accordingly
  - If you don't create additional seeds, all shoots' controlplanes will be hosted on your base cluster and these minimal requirements won't hold


Your next step should be to investigate why the `etcd` doesn't come up. View the logs and do a `kubectl describe` on the etcd statefulset to get more information. Sometimes there are problems with the `PersistentVolumeClaims`, check those - are they ready?
