### ISSUE TITLE
Installation of shoot fails after

### ISSUE THREAD

**Issue by uvwild** [gardener/garden-setup#335]
Installation fails at shoot creation
sow gardencontent/seeds/shoots

trying to install this acre
[acre.zip](https://github.com/gardener/garden-setup/files/5519591/acre.zip)

**Anything else we need to know?**:
on an otc cluster with 7 worker nodes 1 master

**Environment**:
- Version of garden-setup (release or commit)
release 3.2.1 (docker)
- Versions of components (only needed if you overwrote the defaults)
see acre
- Where does the underlying base cluster come from and which operating system does it use?
ubuntu on otc
- Which cloud provider is configured for the setup?
openstack otc

- Other:
The first  installation attempt fails with timeout. it just does not wait long enough. 
When Running Sow again it does not detect the artifacts it created earlier.
I found this. in the debug log
```
lastOperation": {
            "description": "Flow \"Shoot cluster reconciliation\" encountered task errors: [task \"Waiting until shoot worker nodes have been reconciled\" failed: Error while waiting for Worker shoot--garden--otc-seed/otc-seed to become ready: extension encountered error during reconciliation: Error reconciling worker: Failed while waiting for all machine deployments to be ready: '\''machine(s) failed: 1 error occurred: \"shoot--garden--otc-seed-cpu-worker-z1-77848-q574z\": Cloud provider message - error creating the server: Bad request with: [POST https://ecs.eu-de.otc.t-systems.com/v2.1/161aaf61eef04e59bd2a710b98809dc6/servers], error message: {\"badRequest\":{\"message\":\"Multiple security groups found matching shoot--garden--otc-seed. Use an ID to be more specific.\",\"code\":\"400\"}}'\''] Operation will be retried.",

```
I created and destroyed the cluster more than 10 times by now  and the garden-setup never terminates. 
Sometimes its the docker.io pull restrictions. waiting a day helps.

But the scenario above is a good example why it never finishes after.
I think detection of previously created artifacts is a generic issues with this installer. I can fix  this particular issue manually.
But I think I will find more of those conditions moving on.

**Comment by Diaphteiros** [comment]
Hm, there are multiple things here:

First, the error message you quoted doesn't come from garden-setup, but from the Gardener itself. So if the timeout waiting for the worker nodes is too short, this has to be fixed in Gardener or one of its extensions.
The only time garden-setup creates a shoot is when shooted seeds are configured. However, the shoot is created with Gardener and garden-setup has a timeout of 1h waiting for it to be finished - shoots usually come up within this timeframe if there is no error.

Regarding detection of previously created artifacts: If you don't touch the `state` folder, garden-setup should not lose track of kubernetes resources that it creates. It doesn't create resources on the infrastructure directly, apart from the etcd backup bucket, which it also keeps track of. Which artifacts did you have problems with?

**Comment by uvwild** [comment]
I should report  it in the gardener repo then.

Unfortunately, Its not so obvious which part of this huge stack of software is responsible for a failure - in particular for the timeouts.
The challenge is to identify all relevant states of the system in case of the failure

- we have the physical cloud cluster
- an OBS bucket for etcd 
- the  export, gen & state  folders of the garden-setup. 

If one is out of sync, only radical deletion would allow me to carry on. 
I believe to have encountered leftover fragments in all those places at some point. 

Most people using installers dont have a lot of detailed knowledge in the beginning.......
