### ISSUE TITLE
Running the installation using kind

### ISSUE THREAD

**Issue by eladyitz** [gardener/garden-setup#63]
**What would you like to be added**:
I would like to be able to run the installation as part of my CI/CD process using kind as my k8s infrastructure and trvis-ci as my executor

**Why is this needed**:
In order to test applications developed on k8s that depend on Gardener, without utilizing a real cluster in a promise to reduce cost.

**Comment by Diaphteiros** [comment]
Although it would be nice to be able to use garden-setup this way, there are several problems. 

First and most important, Gardener itself does not support kind right now. Pull requests are always welcome, in case you want to extend Gardener, but it's probably a lot of work, since some things work very differently in a local setup (Machines, DNS, everything cloudprovider-specific, ...). 

Another problem is that local development is somewhat out of scope for garden-setup. The main goal of this project is to make it as easy as possible to spin up a Gardener, so everyone who is interested can have a look at it without putting too much effort in. By now it also supports some features that allow to create a near production-grade Gardener. 
However, adding support for kind probably adds lots of complexity - some components can't be deployed anymore or need to be deployed completely differently, e.g. DNS - which disturbs the main purpose of garden-setup.

I will close this issue now, as there is no point in discussing garden-setup support for kind as long as Gardener itself doesn't support kind.
